### ISSUE TITLE
error with json_parse_strict()

### ISSUE THREAD

**Issue by fake-fur** [therobfonz/laravel-mandrill-driver#16]
$response = json_parse_strict((string) $response->getBody());

this is causing exceptions in our app with function not found - any ideas?

laravel 8

**Comment by therobfonz** [comment]
Please try v3.0.3 just released. It may take a few minutes for packagist to fetch the update.

**Comment by fake-fur** [comment]
ok will do

**Comment by fake-fur** [comment]
hi again - i think it is fixed now - had to restart all the queues (forgot that doh!) and so far so good
thank you for the super quick response - seriously
will report back if anything further happens but closing this now

**Comment by therobfonz** [comment]
Glad to hear it worked! I haven't used Mandrill in a while so maintaining this package blindly without being able to test is always challenging.
