### ISSUE TITLE
Laravel 8 Unsupported mail transport [mandrill].

### ISSUE THREAD

**Issue by Morinohtar** [therobfonz/laravel-mandrill-driver#17]
I'm using the lastest Laravel 8 version and I followed the instructions, added:

`'mandrill' => [
        'secret' => env('MANDRILL_SECRET'),
    ],`

To the services.php file. I named in the env file as MANDRILL_SECRET.

Added the Mandrill mailer the config\mail.php:

`
'mandrill' => [
    'transport' => 'mandrill',
],`

And set the MAIL_MAILER in env to:

`MAIL_MAILER=mandrill`

But im getting this error:

`InvalidArgumentException
Unsupported mail transport [mandrill].`

Do i need change anything else? Do we need a host, port, encryption, username, etc?

**Comment by therobfonz** [comment]
Are you using v3.0.3 of this package? There was a update a few weeks back that if you were using some other package, it might cause this issue https://github.com/therobfonz/laravel-mandrill-driver/pull/12

Could also be that package discovery needs to be rerun `php artisan package:discover`

**Comment by therobfonz** [comment]
I believe this is resolved now. Closing and can be reopened if issue remains.
