### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by jnoordsij** [therobfonz/laravel-mandrill-driver#20]
Currently the `composer.json` does not allow [PHP8](https://www.php.net/releases/8.0/en.php). Would be great to have it working. Hopefully you can check this; maybe if I have some spare time later this week I can do some testing if needed.

**Comment by therobfonz** [comment]
Thanks for the comment. I will explore adding support this week, but open to any PRs as well to add support. I no longer use Mandrill so makes it tough to test these changes.

**Comment by jnoordsij** [comment]
Thanks for fixing this. Everything seems to be working fine for me!
