### ISSUE TITLE
PHP 8 Support?

### ISSUE THREAD

**Issue by dinoluck** [therobfonz/laravel-mandrill-driver#22]
- therobfonz/laravel-mandrill-driver[v3.0.0, ..., v3.0.3] require php ^7.3 -> your php version (8.0.1) does not satisfy that requirement.
    - therobfonz/laravel-mandrill-driver v3.0.4 requires guzzlehttp/guzzle ^7.2 -> found guzzlehttp/guzzle[7.2.0] but it conflicts with your root composer.json require (^6.3).
    - Root composer.json requires therobfonz/laravel-mandrill-driver ^3.0 -> satisfiable by therobfonz/laravel-mandrill-driver[v3.0.0, ..., v3.0.4].

Any updates on this?

**Comment by therobfonz** [comment]
This should be resolved in v3.0.4 from this [PR](https://github.com/therobfonz/laravel-mandrill-driver/pull/21). Looks like your Guzzle v6.3 is preventing composer form using the 3.0 tagged release
