### ISSUE TITLE
Not throwing any error and not sending email

### ISSUE THREAD

**Issue by iamwebdev** [therobfonz/laravel-mandrill-driver#23]
I am using laravel8 and mandrill package is configured properly. On sending email, its not showing any error and not even sending email.

**Comment by therobfonz** [comment]
This package is currently in use in many Laravel 8 projects with no issue and it is impossible to help unless you show code. Please check your own projects setup.

**Comment by iamwebdev** [comment]
This is my route:
Route::get('/test-email', function () {
    \Mail::raw('Email service is working fine!!!', function ($message) {
      // dd($message);
        $message->to('abc123@yopmail.com')
        ->cc(['someone@yopmail.com','someone2@yopmail.com'])
        ->bcc(['someone3@yopmail.com','someone4@yopmail.com'])
        ->subject('Email Service Test');
    });
    return 'Email service is running';
});

This is my env
MAIL_MAILER=mandrill
MANDRILL_KEY=my key

Config/app.php (Mailers Array)

'mailers' => [
        'smtp' => [
            'transport' => 'smtp',
            'host' => env('MAIL_HOST', 'smtp.mailgun.org'),
            'port' => env('MAIL_PORT', 587),
            'encryption' => env('MAIL_ENCRYPTION', 'tls'),
            'username' => env('MAIL_USERNAME'),
            'password' => env('MAIL_PASSWORD'),
            'timeout' => null,
            'auth_mode' => null,
        ],

        'ses' => [
            'transport' => 'ses',
        ],

        'mandrill' => [
            'transport' => 'mandrill',
        ],
        
        'mailgun' => [
            'transport' => 'mailgun',
        ],

        'postmark' => [
            'transport' => 'postmark',
        ],

        'sendmail' => [
            'transport' => 'sendmail',
            'path' => '/usr/sbin/sendmail -bs',
        ],

        'log' => [
            'transport' => 'log',
            'channel' => env('MAIL_LOG_CHANNEL'),
        ],

        'array' => [
            'transport' => 'array',
        ],
    ],

My services.php 

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Mailgun, Postmark, AWS and more. This file provides the de facto
    | location for this type of information, allowing packages to have
    | a conventional file to locate the various service credentials.
    |
    */

    'mandrill' => [
        'secret' => env('MANDRILL_KEY'),
    ],
    'mailgun' => [
        'domain' => env('MAILGUN_DOMAIN'),
        'secret' => env('MAILGUN_SECRET'),
        'endpoint' => env('MAILGUN_ENDPOINT', 'api.mailgun.net'),
    ],

    'postmark' => [
        'token' => env('POSTMARK_TOKEN'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

];

Please help me out

**Comment by iamwebdev** [comment]
Please help me out in this, donot mark it is as closed as this issue is not fixed yet.

**Comment by therobfonz** [comment]
This is not a code issue. Github issues is for problems with the actual project, not your personal code and setup. This package is working in many Laravel 8 projects like I said and any issue you are seeing with it not actually sending are because of your personal tech stack.

You need to check your mandrill key and make sure it is not setup as test key. Everything above looks fine as far as setup as far as I can see.

**Comment by iamwebdev** [comment]
This is same mandrill key is working on other project which is working on laravel 5.6, so its not mandrill key issue.

**Comment by iamwebdev** [comment]
SMTP is working fine on laravel 8, but there is some issue with mandrill.
