### ISSUE TITLE
Appears to be broken for Laravel 7

### ISSUE THREAD

**Issue by tpavlek** [therobfonz/laravel-mandrill-driver#3]
In Laravel 7 we're getting errors `Target class [swift.transport] does not exist.` - seems the extension mechanism for mail has changed.

**Comment by therobfonz** [comment]
I will take a look at this shortly.

**Comment by tpavlek** [comment]
Oh looks like it's actually an easy fix. In `MandrillServiceProvder` changing `$this->app['swift.transport']->extend()` to `$this->app['mail.manager']->extend()` fixes it :)

If you'd prefer a pull, I'd be happy to, but that's the easy fix

**Comment by therobfonz** [comment]
Thanks for troubleshooting! I might have to tick this up to version 2.0 if that manager does not exist in 6.0. Looking into that.

**Comment by therobfonz** [comment]
Looks like this will require a major version. I will make the change and push up a 2.0 branch shortly!

**Comment by therobfonz** [comment]
Version 2.0 is tagged and pushed for Laravel 7 support. Let me know if you have any issues!

**Comment by tpavlek** [comment]
Thanks my dude, works great!
