### ISSUE TITLE
How does one specify a Mandrill Template to be used?

### ISSUE THREAD

**Issue by ThaDaVos** [therobfonz/laravel-mandrill-driver#5]
Like the title says, how would one specify the template and mergable vars when sending an email?

(So no blade template, but actualy Mandrill Template)

**Comment by MarkCorneth** [comment]
Also interested in this

**Comment by therobfonz** [comment]
This would require a much larger change outside of the scope of the driver as mailables need to be adjusted to not reference blade files. Unfortunately, not doable without changes at the core of Laravel.

if you are using a Mandrill template, it would be more beneficial to just use their system completely to send the email.
