### ISSUE TITLE
Driver [mandrill] not supported.

### ISSUE THREAD

**Issue by tatvadhaval** [therobfonz/laravel-mandrill-driver#8]
I have upgraded lumen from 5.8 to 6.0 and installed this package, but still getting this error

`[2020-06-05 14:25:14] testing.ERROR: Driver [mandrill] not supported. 

` "php": ">=7.1.3",
        "doctrine/dbal": "^2.10",
        "flipbox/lumen-generator": "6.0",
        "guzzlehttp/guzzle": "^6.3",
        "iatstuti/laravel-cascade-soft-deletes": "3.0.0",
        "illuminate/contracts": "6.8.0",
        "illuminate/mail": "6.x-dev",
        "illuminate/notifications": "6.x-dev",
        "laravel/helpers": "^1.2",
        "laravel/lumen-framework": "^6.0",
        "league/flysystem-aws-s3-v3": "~1.0",
        "scssphp/scssphp": "^1.0",
        "therobfonz/laravel-mandrill-driver": "1.0.1",
        "vlucas/phpdotenv": "^3.3"`

**Comment by therobfonz** [comment]
If you have time to troubleshoot, feel free to submit a PR. v1 of this package was just a direct copy of the old Mandrill driver from the base Laravel repo with no changes. I unfortunately have little to no experience with Lumen to troubleshoot.

**Comment by exeleon** [comment]
@tatvadhaval Add to bootstrap/app.php:

`$app->register(LaravelMandrill\MandrillServiceProvider::class);`

@therobfonz Maybe would be useful to mention in the installation instructions.

**Comment by therobfonz** [comment]
@exeleon feel free to send a PR for the readme if that actually fixes it in Lumen. Since I don't use it, I would like someone who has confirmed it was working there to update the docs.

**Comment by therobfonz** [comment]
Documentation has been updated on the master branch with Lumen instructions.
